# Generated by Django 5.1.4 on 2025-01-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='title',
        ),
    ]
